export const listSkills = [
  "Programming",
  "Data Analysis",
  "Web Development",
  "Graphic Design",
  "Project Management",
  "Digital Marketing",
  "Content Writing",
  "UI/UX Design",
  "Public Speaking",
  "Video Editing",
  "SEO (Search Engine Optimization)",
  "Copywriting",
  "Mobile App Development",
  "Financial Analysis",
  "Photography",
  "Foreign Language Proficiency",
  "Social Media Management",
  "Customer Service",
  "Creative Problem Solving",
  "Leadership",
  "Critical Thinking",
  "Salesmanship",
  "Time Management",
  "Negotiation",
  "Database Management",
];

export const listServices = [
  "Website Development",
  "Mobile App Development",
  "Graphic Design",
  "Digital Marketing Consultation",
  "Content Writing",
  "SEO (Search Engine Optimization)",
  "Social Media Management",
  "Video Production",
  "Photography Services",
  "UI/UX Design",
  "Data Analysis",
  "Financial Consulting",
  "Legal Consultation",
  "Language Translation",
  "Virtual Assistant Services",
  "Event Planning",
  "Fitness Coaching",
  "Nutritional Counseling",
  "Home Cleaning",
  "Personal Styling",
  "Tutoring Services",
  "Interior Design Consultation",
  "Music Lessons",
  "Landscaping Services",
  "Pet Sitting/Dog Walking",
];

export const listLanguages = [
  "English",
  "Spanish",
  "Mandarin Chinese",
  "Hindi",
  "French",
  "Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Swahili",
  "Telugu",
  "Korean",
  "Turkish",
  "Tamil",
  "Italian",
  "Vietnamese",
  "Filipino",
  "Thai",
  "Yoruba",
  "Dutch",
  "Polish",
];

export const proficiencyLevels = [
  {
    label: "Basic",
    description: "I write clearly in this language",
  },
  {
    label: "Conversational",
    description: "I write and speak clearly in this language",
  },
  {
    label: "Fluent",
    description: "I write and speak this language to a high level",
  },
  {
    label: "Native or Bilingual",
    description: "I write and speak this language perfectly",
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic People's Republic of Korea",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia (Federated States of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of Korea",
  "Republic of Moldova",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United Republic of Tanzania",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const techJobs = [
  {
    clientName: "Tech Support Ltd.",
    projectTitle: "IT Support Specialist for Helpdesk Services",
    location: "Onsite",
    verified: true,
    difficulty: "Easy",
    budget: "$2000 - $3000",
    postedDate: "2024-03-31",
    ratings: 3,
    jobDescription:
      "We are looking for an IT support specialist to provide helpdesk services to our internal team. The role involves troubleshooting hardware and software issues, installing software, and assisting users with technical problems.",
    skillsRequired: [
      "Technical Support",
      "Troubleshooting",
      "Helpdesk Support",
      "Hardware",
      "Software",
    ],
  },
  {
    clientName: "TechCo Solutions",
    projectTitle:
      "Senior Full-Stack Developer for E-commerce Platform Enhancement",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-05-01",
    ratings: 4,
    jobDescription:
      "We are looking for an experienced full-stack developer to join our team and help enhance our e-commerce platform. The ideal candidate should have strong skills in both front-end and back-end development, as well as experience with payment gateway integrations.",
    skillsRequired: [
      "JavaScript",
      "React",
      "Node.js",
      "MongoDB",
      "Payment Gateway Integration",
    ],
  },
  {
    clientName: "WebTech Inc.",
    projectTitle: "Front-End Developer for Corporate Website Redesign",
    location: "Hybrid",
    verified: true,
    difficulty: "Intermediate",
    budget: "$2000 - $4000",
    postedDate: "2024-04-08",
    ratings: 4,
    jobDescription:
      "We are looking for a skilled front-end developer to redesign our corporate website. The ideal candidate should have expertise in HTML, CSS, JavaScript, and modern front-end frameworks.",
    skillsRequired: ["HTML", "CSS", "JavaScript", "React", "Responsive Design"],
  },
  {
    clientName: "Data Insights Inc.",
    projectTitle: "Data Scientist for Predictive Analytics Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$5000 - $8000",
    postedDate: "2024-04-09",
    ratings: 5,
    jobDescription:
      "We are seeking a talented data scientist to join our team and work on a predictive analytics project. The role involves analyzing large datasets, building predictive models, and communicating insights to stakeholders.",
    skillsRequired: [
      "Python",
      "Machine Learning",
      "Statistical Analysis",
      "Data Visualization",
      "Predictive Modeling",
    ],
  },

  {
    clientName: "CloudTech Solutions",
    projectTitle: "Cloud Architect for Infrastructure Optimization Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$6000 - $10000",
    postedDate: "2024-04-07",
    ratings: 5,
    jobDescription:
      "We are seeking an experienced cloud architect to optimize our infrastructure for scalability, reliability, and cost-efficiency. The role involves designing and implementing cloud solutions using AWS or Azure.",
    skillsRequired: [
      "AWS",
      "Azure",
      "Cloud Architecture",
      "Infrastructure Optimization",
      "DevOps",
    ],
  },
  {
    clientName: "AI Solutions Ltd.",
    projectTitle:
      "Machine Learning Engineer for Natural Language Processing Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$7000 - $12000",
    postedDate: "2024-04-15",
    ratings: 5,
    jobDescription:
      "We are seeking a talented machine learning engineer to work on a natural language processing project. The role involves developing algorithms, training models, and deploying solutions for text analysis.",
    skillsRequired: [
      "Python",
      "Machine Learning",
      "Natural Language Processing",
      "Deep Learning",
      "TensorFlow",
    ],
  },
  {
    clientName: "MobileApp Innovations",
    projectTitle: "iOS Developer for Mobile App Development Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$4000 - $6000",
    postedDate: "2024-04-06",
    ratings: 4,
    jobDescription:
      "We are looking for an iOS developer to join our team and work on a mobile app development project. The ideal candidate should have experience in Swift programming and building iOS apps.",
    skillsRequired: [
      "Swift",
      "iOS Development",
      "UIKit",
      "RESTful APIs",
      "Git",
    ],
  },

  {
    clientName: "SecurityTech Solutions",
    projectTitle: "Cybersecurity Analyst for Threat Detection Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$5000 - $8000",
    postedDate: "2024-04-24",
    ratings: 4,
    jobDescription:
      "We are looking for a cybersecurity analyst to join our team and work on a threat detection project. The role involves analyzing security data, identifying threats, and implementing detection mechanisms.",
    skillsRequired: [
      "Cybersecurity",
      "Security Operations",
      "Threat Analysis",
      "SIEM",
      "Intrusion Detection",
    ],
  },
  {
    clientName: "Blockchain Innovations",
    projectTitle: "Blockchain Developer for Smart Contract Development",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$6000 - $10000",
    postedDate: "2024-04-03",
    ratings: 5,
    jobDescription:
      "We are seeking a skilled blockchain developer to work on smart contract development. The role involves designing and implementing smart contracts for decentralized applications.",
    skillsRequired: [
      "Blockchain",
      "Solidity",
      "Smart Contracts",
      "Ethereum",
      "Web3.js",
    ],
  },
  {
    clientName: "HealthTech Solutions",
    projectTitle: "Telemedicine App Developer for Healthcare Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$4000 - $7000",
    postedDate: "2024-03-22",
    ratings: 4,
    jobDescription:
      "We are looking for a telemedicine app developer to build a healthcare application. The ideal candidate should have experience in mobile app development and integrating video conferencing APIs.",
    skillsRequired: [
      "Mobile App Development",
      "React Native",
      "Telemedicine",
      "Video Conferencing",
      "Healthcare IT",
    ],
  },
  {
    clientName: "Fintech Innovations",
    projectTitle: "Financial Analyst for Market Research Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-04-01",
    ratings: 4,
    jobDescription:
      "We are seeking a financial analyst to conduct market research and analysis. The role involves gathering financial data, performing industry analysis, and preparing reports.",
    skillsRequired: [
      "Financial Analysis",
      "Market Research",
      "Financial Modeling",
      "Data Analysis",
      "Excel",
    ],
  },
];

export const profileSteps = [
  {
    title: "Employment history",
    isComplete: true,
    description: "Past job experience and positions (+20%)",
  },
  {
    title: "Portfolio",
    isComplete: false,
    description: "Work samples, case studies, e.t.c (+20%)",
  },
  {
    title: "Education",
    isComplete: true,
    description: "Include some college, degree or diplomas (+10%)",
  },
  {
    title: "Certifications",
    isComplete: false,
    description: "Recognized skills and knowledge (+10%)",
  },
  {
    title: "Other experience",
    isComplete: false,
    description: "Bootcamps, conferences, awards e.t.c (+5%)",
  },
];