export const listSkills = [
  "Programming",
  "Data Analysis",
  "Web Development",
  "Graphic Design",
  "Project Management",
  "Digital Marketing",
  "Content Writing",
  "UI/UX Design",
  "Public Speaking",
  "Video Editing",
  "SEO (Search Engine Optimization)",
  "Copywriting",
  "Mobile App Development",
  "Financial Analysis",
  "Photography",
  "Foreign Language Proficiency",
  "Social Media Management",
  "Customer Service",
  "Creative Problem Solving",
  "Leadership",
  "Critical Thinking",
  "Salesmanship",
  "Time Management",
  "Negotiation",
  "Database Management",
];

export const listServices = [
  "Website Development",
  "Mobile App Development",
  "Graphic Design",
  "Digital Marketing Consultation",
  "Content Writing",
  "SEO (Search Engine Optimization)",
  "Social Media Management",
  "Video Production",
  "Photography Services",
  "UI/UX Design",
  "Data Analysis",
  "Financial Consulting",
  "Legal Consultation",
  "Language Translation",
  "Virtual Assistant Services",
  "Event Planning",
  "Fitness Coaching",
  "Nutritional Counseling",
  "Home Cleaning",
  "Personal Styling",
  "Tutoring Services",
  "Interior Design Consultation",
  "Music Lessons",
  "Landscaping Services",
  "Pet Sitting/Dog Walking",
];

export const listLanguages = [
  "English",
  "Spanish",
  "Mandarin Chinese",
  "Hindi",
  "French",
  "Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Swahili",
  "Telugu",
  "Korean",
  "Turkish",
  "Tamil",
  "Italian",
  "Vietnamese",
  "Filipino",
  "Thai",
  "Yoruba",
  "Dutch",
  "Polish",
];

export const proficiencyLevels = [
  {
    label: "Basic",
    description: "I write clearly in this language",
  },
  {
    label: "Conversational",
    description: "I write and speak clearly in this language",
  },
  {
    label: "Fluent",
    description: "I write and speak this language to a high level",
  },
  {
    label: "Native or Bilingual",
    description: "I write and speak this language perfectly",
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic People's Republic of Korea",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia (Federated States of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of Korea",
  "Republic of Moldova",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United Republic of Tanzania",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const techJobs = [
  {
    id: 980,
    clientName: "TechCo Solutions",
    projectTitle: "Senior Full-Stack Developer for E-commerce Platform Enhancement",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-04-10",
    ratings: 4,
    jobDescription: "We are looking for an experienced full-stack developer to join our team and help enhance our e-commerce platform. The ideal candidate should have strong skills in both front-end and back-end development, as well as experience with payment gateway integrations.",
    skillsRequired: ["JavaScript", "React", "Node.js", "MongoDB", "Payment Gateway Integration"]
  },
  {
    id: 245,
    clientName: "Data Insights Inc.",
    projectTitle: "Data Scientist for Predictive Analytics Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$5000 - $8000",
    postedDate: "2024-04-09",
    ratings: 5,
    jobDescription: "We are seeking a talented data scientist to join our team and work on a predictive analytics project. The role involves analyzing large datasets, building predictive models, and communicating insights to stakeholders.",
    skillsRequired: ["Python", "Machine Learning", "Statistical Analysis", "Data Visualization", "Predictive Modeling"]
  },
  {
    id: 2109,
    clientName: "WebTech Inc.",
    projectTitle: "Front-End Developer for Corporate Website Redesign",
    location: "Hybrid",
    verified: true,
    difficulty: "Intermediate",
    budget: "$2000 - $4000",
    postedDate: "2024-04-08",
    ratings: 4,
    jobDescription: "We are looking for a skilled front-end developer to redesign our corporate website. The ideal candidate should have expertise in HTML, CSS, JavaScript, and modern front-end frameworks.",
    skillsRequired: ["HTML", "CSS", "JavaScript", "React", "Responsive Design"]
  },
  {
    id: 2999,
    clientName: "CloudTech Solutions",
    projectTitle: "Cloud Architect for Infrastructure Optimization Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$6000 - $10000",
    postedDate: "2024-04-07",
    ratings: 5,
    jobDescription: "We are seeking an experienced cloud architect to optimize our infrastructure for scalability, reliability, and cost-efficiency. The role involves designing and implementing cloud solutions using AWS or Azure.",
    skillsRequired: ["AWS", "Azure", "Cloud Architecture", "Infrastructure Optimization", "DevOps"]
  },
  {
    id: 3029,
    clientName: "MobileApp Innovations",
    projectTitle: "iOS Developer for Mobile App Development Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$4000 - $6000",
    postedDate: "2024-04-06",
    ratings: 4,
    jobDescription: "We are looking for an iOS developer to join our team and work on a mobile app development project. The ideal candidate should have experience in Swift programming and building iOS apps.",
    skillsRequired: ["Swift", "iOS Development", "UIKit", "RESTful APIs", "Git"]
  },
  {
    id: 2039,
    clientName: "AI Solutions Ltd.",
    projectTitle: "Machine Learning Engineer for Natural Language Processing Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$7000 - $12000",
    postedDate: "2024-04-05",
    ratings: 5,
    jobDescription: "We are seeking a talented machine learning engineer to work on a natural language processing project. The role involves developing algorithms, training models, and deploying solutions for text analysis.",
    skillsRequired: ["Python", "Machine Learning", "Natural Language Processing", "Deep Learning", "TensorFlow"]
  },
  {
    id: 1092,
    clientName: "SecurityTech Solutions",
    projectTitle: "Cybersecurity Analyst for Threat Detection Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$5000 - $8000",
    postedDate: "2024-04-04",
    ratings: 4,
    jobDescription: "We are looking for a cybersecurity analyst to join our team and work on a threat detection project. The role involves analyzing security data, identifying threats, and implementing detection mechanisms.",
    skillsRequired: ["Cybersecurity", "Security Operations", "Threat Analysis", "SIEM", "Intrusion Detection"]
  },
  {
    id: 9087,
    clientName: "Blockchain Innovations",
    projectTitle: "Blockchain Developer for Smart Contract Development",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$6000 - $10000",
    postedDate: "2024-04-03",
    ratings: 5,
    jobDescription: "We are seeking a skilled blockchain developer to work on smart contract development. The role involves designing and implementing smart contracts for decentralized applications.",
    skillsRequired: ["Blockchain", "Solidity", "Smart Contracts", "Ethereum", "Web3.js"]
  },
  {
    id: 857,
    clientName: "HealthTech Solutions",
    projectTitle: "Telemedicine App Developer for Healthcare Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$4000 - $7000",
    postedDate: "2024-04-02",
    ratings: 4,
    jobDescription: "We are looking for a telemedicine app developer to build a healthcare application. The ideal candidate should have experience in mobile app development and integrating video conferencing APIs.",
    skillsRequired: ["Mobile App Development", "React Native", "Telemedicine", "Video Conferencing", "Healthcare IT"]
  },
  {
    id: 1902,
    clientName: "Fintech Innovations",
    projectTitle: "Financial Analyst for Market Research Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-04-01",
    ratings: 4,
    jobDescription: "We are seeking a financial analyst to conduct market research and analysis. The role involves gathering financial data, performing industry analysis, and preparing reports.",
    skillsRequired: ["Financial Analysis", "Market Research", "Financial Modeling", "Data Analysis", "Excel"]
  },
  {
    id: 3103,
    clientName: "Tech Support Ltd.",
    projectTitle: "IT Support Specialist for Helpdesk Services",
    location: "Onsite",
    verified: true,
    difficulty: "Easy",
    budget: "$2000 - $3000",
    postedDate: "2024-03-31",
    ratings: 3,
    jobDescription: "We are looking for an IT support specialist to provide helpdesk services to our internal team. The role involves troubleshooting hardware and software issues, installing software, and assisting users with technical problems.",
    skillsRequired: ["Technical Support", "Troubleshooting", "Helpdesk Support", "Hardware", "Software"]
  },
  {
    id: 458,
    clientName: "EdTech Innovations",
    projectTitle: "E-learning Developer for Course Content Creation",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$4000 - $6000",
    postedDate: "2024-03-30",
    ratings: 4,
    jobDescription: "We are seeking an e-learning developer to create course content for online education platforms. The ideal candidate should have experience in instructional design, multimedia production, and learning management systems.",
    skillsRequired: ["Instructional Design", "E-learning Development", "Multimedia Production", "Learning Management Systems", "Educational Technology"]
  },
  {
    id: 4096,
    clientName: "AI Solutions Ltd.",
    projectTitle: "Computer Vision Engineer for Image Recognition Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$6000 - $10000",
    postedDate: "2024-03-29",
    ratings: 5,
    jobDescription: "We are looking for a computer vision engineer to work on an image recognition project. The role involves developing algorithms for object detection, image segmentation, and feature extraction.",
    skillsRequired: ["Computer Vision", "Image Processing", "Deep Learning", "Python", "OpenCV"]
  },
  {
    id: 240,
    clientName: "GameTech Innovations",
    projectTitle: "Game Developer for Mobile Game Development Project",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$5000 - $8000",
    postedDate: "2024-03-28",
    ratings: 4,
    jobDescription: "We are seeking a game developer to work on a mobile game development project. The ideal candidate should have experience in game design, Unity development, and mobile game optimization.",
    skillsRequired: ["Game Development", "Unity", "C#", "Mobile Game Development", "Game Design"]
  },
  {
    id: 26,
    clientName: "Social Media Solutions",
    projectTitle: "Social Media Manager for Marketing Campaign",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-03-27",
    ratings: 4,
    jobDescription: "We are looking for a social media manager to oversee our marketing campaign on various social media platforms. The role involves creating content, scheduling posts, and analyzing performance metrics.",
    skillsRequired: ["Social Media Management", "Content Creation", "Marketing", "Analytics", "Copywriting"]
  },
  {
    id: 2,
    clientName: "WebTech Innovations",
    projectTitle: "Back-End Developer for Web Application Development",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$4000 - $6000",
    postedDate: "2024-03-26",
    ratings: 4,
    jobDescription: "We are seeking a back-end developer to work on a web application development project. The ideal candidate should have expertise in server-side programming, database management, and API integration.",
    skillsRequired: ["Node.js", "Express.js", "MongoDB", "RESTful APIs", "Server-Side Programming"]
  },
  {
    id: 89,
    clientName: "HealthTech Solutions",
    projectTitle: "UI/UX Designer for Healthcare App Redesign",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-03-25",
    ratings: 4,
    jobDescription: "We are looking for a UI/UX designer to redesign our healthcare application. The ideal candidate should have experience in user interface design, user experience research, and prototyping tools.",
    skillsRequired: ["UI Design", "UX Design", "Prototyping", "User Research", "Adobe XD"]
  },
  {
    id: 40000,
    clientName: "FinanceTech Solutions",
    projectTitle: "Quantitative Analyst for Algorithmic Trading Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$8000 - $15000",
    postedDate: "2024-03-24",
    ratings: 5,
    jobDescription: "We are seeking a quantitative analyst to work on an algorithmic trading project. The role involves developing trading strategies, backtesting algorithms, and optimizing trading models.",
    skillsRequired: ["Quantitative Analysis", "Algorithmic Trading", "Financial Modeling", "Python", "Data Analysis"]
  },
  {
    id: 23,
    clientName: "AI Solutions Ltd.",
    projectTitle: "Natural Language Processing Engineer for Chatbot Development",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$6000 - $10000",
    postedDate: "2024-03-23",
    ratings: 5,
    jobDescription: "We are looking for a natural language processing engineer to work on chatbot development. The role involves designing conversational interfaces, implementing NLP algorithms, and training chatbot models.",
    skillsRequired: ["Natural Language Processing", "Chatbot Development", "Machine Learning", "Python", "NLP Libraries"]
  },
  {
    id: 1,
    clientName: "EduTech Innovations",
    projectTitle: "Instructional Designer for Online Course Development",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-03-22",
    ratings: 4,
    jobDescription: "We are seeking an instructional designer to develop online courses for our e-learning platform. The ideal candidate should have experience in curriculum design, instructional strategies, and e-learning technologies.",
    skillsRequired: ["Instructional Design", "Curriculum Development", "E-learning", "Educational Technology", "Course Authoring Tools"]
  },
  {
    id: 392,
    clientName: "MarketingTech Solutions",
    projectTitle: "Digital Marketing Specialist for SEO Campaign",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$3000 - $5000",
    postedDate: "2024-03-21",
    ratings: 4,
    jobDescription: "We are looking for a digital marketing specialist to manage our SEO campaign. The role involves keyword research, on-page optimization, link building, and performance tracking.",
    skillsRequired: ["SEO", "Digital Marketing", "Keyword Research", "Link Building", "Analytics"]
  },
  {
    id: 209,
    clientName: "CloudTech Innovations",
    projectTitle: "DevOps Engineer for Continuous Integration/Continuous Deployment (CI/CD)",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$6000 - $10000",
    postedDate: "2024-03-20",
    ratings: 5,
    jobDescription: "We are seeking a DevOps engineer to implement continuous integration/continuous deployment (CI/CD) pipelines. The role involves automating build, test, and deployment processes for cloud-native applications.",
    skillsRequired: ["DevOps", "CI/CD", "Automation", "Cloud Computing", "Containerization"]
  },
  {
    id: 20,
    clientName: "Data Insights Inc.",
    projectTitle: "Business Intelligence Analyst for Dashboard Development",
    location: "Remote",
    verified: true,
    difficulty: "Intermediate",
    budget: "$4000 - $6000",
    postedDate: "2024-03-19",
    ratings: 4,
    jobDescription: "We are looking for a business intelligence analyst to develop interactive dashboards for data visualization. The role involves gathering business requirements, designing data models, and creating visualizations.",
    skillsRequired: ["Business Intelligence", "Data Visualization", "Dashboard Development", "SQL", "Tableau"]
  },
  {
    id: 30,
    clientName: "SecurityTech Solutions",
    projectTitle: "Penetration Tester for Security Assessment Project",
    location: "Remote",
    verified: true,
    difficulty: "Experience",
    budget: "$7000 - $12000",
    postedDate: "2024-03-18",
    ratings: 5,
    jobDescription: "We are seeking a penetration tester to conduct security assessments of our systems and networks. The role involves identifying vulnerabilities, performing penetration tests, and recommending security solutions.",
    skillsRequired: ["Penetration Testing", "Ethical Hacking", "Vulnerability Assessment", "Network Security", "Security Tools"]
  },
];

export const profileSteps = [
  {
    title: "Employment history",
    isComplete: true,
    description: "Past job experience and positions (+20%)",
  },
  {
    title: "Portfolio",
    isComplete: false,
    description: "Work samples, case studies, e.t.c (+20%)",
  },
  {
    title: "Education",
    isComplete: true,
    description: "Include some college, degree or diplomas (+10%)",
  },
  {
    title: "Certifications",
    isComplete: false,
    description: "Recognized skills and knowledge (+10%)",
  },
  {
    title: "Other experience",
    isComplete: false,
    description: "Bootcamps, conferences, awards e.t.c (+5%)",
  },
];