/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/pages/**/*.{js,ts,jsx,tsx,mdx}', './src/components/**/*.{js,ts,jsx,tsx,mdx}', './src/app/**/*.{js,ts,jsx,tsx,mdx}'],
	theme: {
	  extend: {
	    backgroundImage: {
	      "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
	      "gradient-conic":
	        "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
	    },
	  },
	},
	// theme: {
	// 	extend: {
	// 		colors: {
	// 			black: 'var(--black)',
	// 			'foundation-successsuccess-100': 'var(--foundation-successsuccess-100)',
	// 			'foundation-successsuccess-200': 'var(--foundation-successsuccess-200)',
	// 			'foundation-successsuccess-300': 'var(--foundation-successsuccess-300)',
	// 			'foundation-successsuccess-400': 'var(--foundation-successsuccess-400)',
	// 			'foundation-successsuccess-50': 'var(--foundation-successsuccess-50)',
	// 			'foundation-successsuccess-500': 'var(--foundation-successsuccess-500)',
	// 			'foundation-successsuccess-600': 'var(--foundation-successsuccess-600)',
	// 			'foundation-successsuccess-700': 'var(--foundation-successsuccess-700)',
	// 			'foundation-successsuccess-800': 'var(--foundation-successsuccess-800)',
	// 			'foundation-successsuccess-900': 'var(--foundation-successsuccess-900)',
	// 			'foundationerrorerror-100': 'var(--foundationerrorerror-100)',
	// 			'foundationerrorerror-200': 'var(--foundationerrorerror-200)',
	// 			'foundationerrorerror-25': 'var(--foundationerrorerror-25)',
	// 			'foundationerrorerror-300': 'var(--foundationerrorerror-300)',
	// 			'foundationerrorerror-400': 'var(--foundationerrorerror-400)',
	// 			'foundationerrorerror-50': 'var(--foundationerrorerror-50)',
	// 			'foundationerrorerror-500': 'var(--foundationerrorerror-500)',
	// 			'foundationerrorerror-600': 'var(--foundationerrorerror-600)',
	// 			'foundationerrorerror-700': 'var(--foundationerrorerror-700)',
	// 			'foundationerrorerror-800': 'var(--foundationerrorerror-800)',
	// 			'foundationerrorerror-900': 'var(--foundationerrorerror-900)',
	// 			'foundationgreygrey-100': 'var(--foundationgreygrey-100)',
	// 			'foundationgreygrey-200': 'var(--foundationgreygrey-200)',
	// 			'foundationgreygrey-25': 'var(--foundationgreygrey-25)',
	// 			'foundationgreygrey-300': 'var(--foundationgreygrey-300)',
	// 			'foundationgreygrey-400': 'var(--foundationgreygrey-400)',
	// 			'foundationgreygrey-50': 'var(--foundationgreygrey-50)',
	// 			'foundationgreygrey-500': 'var(--foundationgreygrey-500)',
	// 			'foundationgreygrey-600': 'var(--foundationgreygrey-600)',
	// 			'foundationgreygrey-700': 'var(--foundationgreygrey-700)',
	// 			'foundationgreygrey-800': 'var(--foundationgreygrey-800)',
	// 			'foundationgreygrey-900': 'var(--foundationgreygrey-900)',
	// 			'foundationprimaryprimary-100': 'var(--foundationprimaryprimary-100)',
	// 			'foundationprimaryprimary-200': 'var(--foundationprimaryprimary-200)',
	// 			'foundationprimaryprimary-25': 'var(--foundationprimaryprimary-25)',
	// 			'foundationprimaryprimary-300': 'var(--foundationprimaryprimary-300)',
	// 			'foundationprimaryprimary-400': 'var(--foundationprimaryprimary-400)',
	// 			'foundationprimaryprimary-50': 'var(--foundationprimaryprimary-50)',
	// 			'foundationprimaryprimary-500': 'var(--foundationprimaryprimary-500)',
	// 			'foundationprimaryprimary-600': 'var(--foundationprimaryprimary-600)',
	// 			'foundationprimaryprimary-700': 'var(--foundationprimaryprimary-700)',
	// 			'foundationprimaryprimary-800': 'var(--foundationprimaryprimary-800)',
	// 			'foundationprimaryprimary-900': 'var(--foundationprimaryprimary-900)',
	// 			'foundationpurplepurple-100': 'var(--foundationpurplepurple-100)',
	// 			'foundationpurplepurple-200': 'var(--foundationpurplepurple-200)',
	// 			'foundationpurplepurple-25': 'var(--foundationpurplepurple-25)',
	// 			'foundationpurplepurple-300': 'var(--foundationpurplepurple-300)',
	// 			'foundationpurplepurple-400': 'var(--foundationpurplepurple-400)',
	// 			'foundationpurplepurple-50': 'var(--foundationpurplepurple-50)',
	// 			'foundationpurplepurple-500': 'var(--foundationpurplepurple-500)',
	// 			'foundationpurplepurple-600': 'var(--foundationpurplepurple-600)',
	// 			'foundationpurplepurple-700': 'var(--foundationpurplepurple-700)',
	// 			'foundationpurplepurple-800': 'var(--foundationpurplepurple-800)',
	// 			'foundationpurplepurple-900': 'var(--foundationpurplepurple-900)',
	// 			'foundationsuccesssuccess-25': 'var(--foundationsuccesssuccess-25)',
	// 			'foundationwarning-colourwarning-colour-100': 'var(--foundationwarning-colourwarning-colour-100)',
	// 			'foundationwarning-colourwarning-colour-200': 'var(--foundationwarning-colourwarning-colour-200)',
	// 			'foundationwarning-colourwarning-colour-25': 'var(--foundationwarning-colourwarning-colour-25)',
	// 			'foundationwarning-colourwarning-colour-300': 'var(--foundationwarning-colourwarning-colour-300)',
	// 			'foundationwarning-colourwarning-colour-400': 'var(--foundationwarning-colourwarning-colour-400)',
	// 			'foundationwarning-colourwarning-colour-50': 'var(--foundationwarning-colourwarning-colour-50)',
	// 			'foundationwarning-colourwarning-colour-500': 'var(--foundationwarning-colourwarning-colour-500)',
	// 			'foundationwarning-colourwarning-colour-600': 'var(--foundationwarning-colourwarning-colour-600)',
	// 			'foundationwarning-colourwarning-colour-700': 'var(--foundationwarning-colourwarning-colour-700)',
	// 			'foundationwarning-colourwarning-colour-800': 'var(--foundationwarning-colourwarning-colour-800)',
	// 			'foundationwarning-colourwarning-colour-900': 'var(--foundationwarning-colourwarning-colour-900)',
	// 			white: 'var(--white)',
	// 		},
	// 		fontFamily: {
	// 			'b8-regular': 'var(--b8-regular-font-family)',
	// 			'desktop-headings-display-large-black': 'var(--desktop-headings-display-large-black-font-family)',
	// 			'desktop-headings-display-large-bold': 'var(--desktop-headings-display-large-bold-font-family)',
	// 			'desktop-headings-display-large-medium': 'var(--desktop-headings-display-large-medium-font-family)',
	// 			'desktop-headings-display-large-regular': 'var(--desktop-headings-display-large-regular-font-family)',
	// 			'desktop-headings-display-small-black': 'var(--desktop-headings-display-small-black-font-family)',
	// 			'desktop-headings-display-small-bold': 'var(--desktop-headings-display-small-bold-font-family)',
	// 			'desktop-headings-display-small-medium': 'var(--desktop-headings-display-small-medium-font-family)',
	// 			'desktop-headings-display-small-regular': 'var(--desktop-headings-display-small-regular-font-family)',
	// 			'desktop-headings-heading-h1-black': 'var(--desktop-headings-heading-h1-black-font-family)',
	// 			'desktop-headings-heading-h1-bold': 'var(--desktop-headings-heading-h1-bold-font-family)',
	// 			'desktop-headings-heading-h1-medium': 'var(--desktop-headings-heading-h1-medium-font-family)',
	// 			'desktop-headings-heading-h1-regular': 'var(--desktop-headings-heading-h1-regular-font-family)',
	// 			'desktop-headings-heading-h2-black': 'var(--desktop-headings-heading-h2-black-font-family)',
	// 			'desktop-headings-heading-h2-bold': 'var(--desktop-headings-heading-h2-bold-font-family)',
	// 			'desktop-headings-heading-h2-medium': 'var(--desktop-headings-heading-h2-medium-font-family)',
	// 			'desktop-headings-heading-h2-regular': 'var(--desktop-headings-heading-h2-regular-font-family)',
	// 			'desktop-headings-heading-h3-black': 'var(--desktop-headings-heading-h3-black-font-family)',
	// 			'desktop-headings-heading-h3-bold': 'var(--desktop-headings-heading-h3-bold-font-family)',
	// 			'desktop-headings-heading-h3-medium': 'var(--desktop-headings-heading-h3-medium-font-family)',
	// 			'desktop-headings-heading-h3-regular': 'var(--desktop-headings-heading-h3-regular-font-family)',
	// 			'desktop-headings-heading-h4-black': 'var(--desktop-headings-heading-h4-black-font-family)',
	// 			'desktop-headings-heading-h4-bold': 'var(--desktop-headings-heading-h4-bold-font-family)',
	// 			'desktop-headings-heading-h4-medium': 'var(--desktop-headings-heading-h4-medium-font-family)',
	// 			'desktop-headings-heading-h4-regular': 'var(--desktop-headings-heading-h4-regular-font-family)',
	// 			'desktop-headings-heading-h5-black': 'var(--desktop-headings-heading-h5-black-font-family)',
	// 			'desktop-headings-heading-h5-bold': 'var(--desktop-headings-heading-h5-bold-font-family)',
	// 			'desktop-headings-heading-h5-medium': 'var(--desktop-headings-heading-h5-medium-font-family)',
	// 			'desktop-headings-heading-h5-regular': 'var(--desktop-headings-heading-h5-regular-font-family)',
	// 			'desktop-headings-heading-h6-black': 'var(--desktop-headings-heading-h6-black-font-family)',
	// 			'desktop-headings-heading-h6-bold': 'var(--desktop-headings-heading-h6-bold-font-family)',
	// 			'desktop-headings-heading-h6-medium': 'var(--desktop-headings-heading-h6-medium-font-family)',
	// 			'desktop-headings-heading-h6-regular': 'var(--desktop-headings-heading-h6-regular-font-family)',
	// 			'paragraph-large-bold': 'var(--paragraph-large-bold-font-family)',
	// 			'paragraph-large-italics': 'var(--paragraph-large-italics-font-family)',
	// 			'paragraph-large-medium': 'var(--paragraph-large-medium-font-family)',
	// 			'paragraph-large-regular': 'var(--paragraph-large-regular-font-family)',
	// 			'paragraph-medium-bold': 'var(--paragraph-medium-bold-font-family)',
	// 			'paragraph-medium-italics': 'var(--paragraph-medium-italics-font-family)',
	// 			'paragraph-medium-medium': 'var(--paragraph-medium-medium-font-family)',
	// 			'paragraph-medium-regular': 'var(--paragraph-medium-regular-font-family)',
	// 			'paragraph-small-bold': 'var(--paragraph-small-bold-font-family)',
	// 			'paragraph-small-italics': 'var(--paragraph-small-italics-font-family)',
	// 			'paragraph-small-medium': 'var(--paragraph-small-medium-font-family)',
	// 			'paragraph-small-regular': 'var(--paragraph-small-regular-font-family)',
	// 			'paragraph-XL-bold': 'var(--paragraph-XL-bold-font-family)',
	// 			'paragraph-XL-italics': 'var(--paragraph-XL-italics-font-family)',
	// 			'paragraph-XL-medium': 'var(--paragraph-XL-medium-font-family)',
	// 			'paragraph-XL-regular': 'var(--paragraph-XL-regular-font-family)',
	// 			'paragraph-xsmall-bold': 'var(--paragraph-xsmall-bold-font-family)',
	// 			'paragraph-xsmall-italics': 'var(--paragraph-xsmall-italics-font-family)',
	// 			'paragraph-xsmall-medium': 'var(--paragraph-xsmall-medium-font-family)',
	// 			'paragraph-xsmall-regular': 'var(--paragraph-xsmall-regular-font-family)',
	// 		},
	// 		boxShadow: {
	// 			'a-TTENTION': 'var(--a-TTENTION)',
	// 			'highlight-shadow': 'var(--highlight-shadow)',
	// 			'illustartion-shadow': 'var(--illustartion-shadow)',
	// 			'modal-shdow': 'var(--modal-shdow)',
	// 		},
	// 	},
	// },
	plugins: [],
};
