export const listSkills = [
  "Programming",
  "Data Analysis",
  "Web Development",
  "Graphic Design",
  "Project Management",
  "Digital Marketing",
  "Content Writing",
  "UI/UX Design",
  "Public Speaking",
  "Video Editing",
  "SEO (Search Engine Optimization)",
  "Copywriting",
  "Mobile App Development",
  "Financial Analysis",
  "Photography",
  "Foreign Language Proficiency",
  "Social Media Management",
  "Customer Service",
  "Creative Problem Solving",
  "Leadership",
  "Critical Thinking",
  "Salesmanship",
  "Time Management",
  "Negotiation",
  "Database Management",
];
